spring:
  cloud:
    nacos:
      server-addr: 192.168.88.100:8848
    sentinel:
      transport:
        dashboard: localhost:8090
      http-method-specify: true

jlu:
  jwt:
    sharding: true
    location: classpath:auth-service.jks
    alias: hmall
    password: "hmall123"
    tokenTTL: 30m

server:
  port: 8081
  tomcat:
    threads:
      max: 50
    accept-count: 50
    max-connection: 100