spring:
  cloud:
    nacos:
      server-addr: 192.168.88.100:8848

jlu:
  jwt:
    sharding: true
    location: classpath:auth-service.jks
    alias: hmall
    password: "hmall123"
    tokenTTL: 30m

web:
  db:
    host: 192.168.88.100
    pw: 1234
