spring:
  data:
    redis:
      repositories:
        enabled: false
  profiles:
    include: redis

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: "classpath*:/mapper/**/*.xml"

