spring.application.name=springboot-web

#?????

#?????url??
spring.datasource.url = jdbc:mysql://localhost:3306/notes_database
#???????
spring.datasource.driver-class-name = "com.mysql.cj.jdbc.Driver"

spring.datasource.username = mysql80
spring.datasource.password = 1234





