server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.88.100:8848
    gateway:
      routes:
        - id: take-note
          uri: lb://take-note
          predicates:
            - Path=/notebook/**
        - id: user
          uri: lb://auth-service
          predicates:
            - Path=/user/**

jlu:
  jwt:
    sharding: true
    location: classpath:auth-service.jks
    alias: hmall
    password: "hmall123"
    tokenTTL: 30m
  auth:
    exclude-Paths:
      - /user/login
      - /user/register